eshost: "localhost"
esport: "9200"
interval: 10
alert:
 mailto: "hoge@fuga.hoge"
 mailfrom: "fuga@hoge.futa"
 password: "pass"
 tmpl-dstat-cpu-title: "[monitoring-{server}]ALERT: cpu-used {value}%"
 tmpl-dstat-cpu-msg: "CPU大丈夫？"
 tmpl-dstat-disk-title: "[monitoring-{server}]ALERT: disk-used {value}%"
 tmpl-dstat-disk-msg: "DISK大丈夫？"
 tmpl-dstat-mem-title: "[monitoring-{server}]ALERT: mem-used {value}%"
 tmpl-dstat-mem-msg: "MEM大丈夫？"
dstat:
 - server: "es type name"
   cpu-threshold: 80
   disk-threshold: 80
   mem-threshold: 80
